### ISSUE TITLE
How have you trained this model

### ISSUE THREAD

**Issue by surendrallam** [amolikvivian/Caffe-SSD-Object-Detection#2]
Hi,
How have you trained this model, we want to train with our custom dataset, please provide reference.

Thanks in advance.

**Comment by amolikvivian** [comment]
Hi Surendra

The weights I used in this repository were pretrained, you can find them at https://caffe.berkeleyvision.org/model_zoo.html just to test out Caffe's FPS and accuracy.

I found this article to be a great way of training a custom dataset - https://chunml.github.io/ChunML.github.io/project/Training-Your-Own-Data-On-Caffe/

Hope it helpds

**Comment by amolikvivian** [comment]
helps*

**Comment by surendrallam** [comment]
Could u send me reference link for custom dataset training for SSD MobileNet.

Thanks and Regards,
Surendra Allam.

Sent from my iPhone

On 09-Dec-2020, at 5:00 PM, Amolik Vivian Paul <notifications@github.com> wrote:

﻿

helps*
