### ISSUE TITLE
Dataset used for training

### ISSUE THREAD

**Issue by surendrallam** [amolikvivian/Caffe-SSD-Object-Detection#4]
What dataset has been used for tranning?

**Comment by amolikvivian** [comment]
The pretrained model, Caffe MobileNet SSD, was originally trained on the COCO dataset (https://cocodataset.org/)

**Comment by surendrallam** [comment]
Thank you so much for the information.


Thanks and Regards,
Surendra Allam.

**Comment by amolikvivian** [comment]
You're welcome!
